### ISSUE TITLE
Finer grained user creation

### ISSUE THREAD

**Issue by danielrichman** [ukhas/habcloud-salt-states#1]
Maybe have pillar

```
users:
    simon:
        boxes: 'postgres* or ukhas'
        sudo: 'ukhas'
```

and then use

``` jinja
{% if salt['match.compound'](data.boxes) %}
....
```
