### ISSUE TITLE
saltbot's pip.installed always reports changes

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habcloud-salt-states#2]
```
      ID: saltbot-install
Function: pip.installed
  Result: True
 Comment: Package successfully installed from VCS checkout /home/saltbot/saltbot.
 Started: 00:33:08.309761
Duration: 562.073 ms
 Changes:   
          ----------
          editable:
              True
```

Every time you highstate, this happens, so it always sees a change. Might be related to https://github.com/saltstack/salt/issues/5211
